version: '3.3'

services:
  minecraft:
    build:
      context: minecraft
    restart: always
    volumes:
      - ./volumes/data:/etc/minecraft/data:rw
      - ./volumes/backups:/etc/minecraft/backups:rw
      - ./volumes/bin:/etc/minecraft/bin:rw
    ports:
      - "25565:25565"
    environment:
      CUSTOM_BACKUP_TIME: 0620

