version: '3.3'

services:
  minecraft:
    image: minecraft:<server version>
    restart: always
    volumes:
      - <your minecraft data dir>:/etc/minecraft/data:rw
      - <your minecraft backups dir>:/etc/minecraft/backups:rw
    ports:
      - "25565:25565"
    environment:
      CUSTOM_BACKUP_TIME: 0620

